#!/bin/bash
# =============================================================================
# compat/lib/detect-platform.sh — Platform/vendor fingerprint detector
# =============================================================================
# Reads /vendor/build.prop, /odm/etc/build.prop and /system/build.prop to
# extract the values needed by quirks.json matchers. Outputs a flat shell
# eval-friendly variable list (KEY=VALUE) plus a JSON snapshot used by the
# diagnostics aggregator.
#
# Inspired by:
#   - device_phh_treble (system.prop / phh-prop-handler.sh)
#   - vendor_hardware_overlay (per-brand overlay selection)
#   - TrebleDroid/treble_app — Misc.kt SystemProperties readers
# =============================================================================

set -u

COMPAT_RUN_DIR="${COMPAT_RUN_DIR:-/run/ubuntu-gsi/compat}"
COMPAT_PROP_SNAPSHOT="${COMPAT_PROP_SNAPSHOT:-$COMPAT_RUN_DIR/platform.json}"
COMPAT_PROP_ENV="${COMPAT_PROP_ENV:-$COMPAT_RUN_DIR/platform.env}"

mkdir -p "$COMPAT_RUN_DIR" 2>/dev/null || true

# ---------------------------------------------------------------------------
# read_prop KEY [FALLBACK_KEY ...]
#   Returns the first non-empty value across all known build.prop locations.
# ---------------------------------------------------------------------------
COMPAT_BUILD_PROPS=(
    /vendor/build.prop
    /vendor/default.prop
    /odm/etc/build.prop
    /odm/build.prop
    /system/build.prop
    /system/system_ext/etc/build.prop
    /product/build.prop
)

read_prop() {
    local key val
    for key in "$@"; do
        for f in "${COMPAT_BUILD_PROPS[@]}"; do
            [ -r "$f" ] || continue
            val=$(awk -F= -v k="$key" '$1==k {sub(/^[^=]*=/,""); print; exit}' "$f" 2>/dev/null)
            if [ -n "$val" ]; then
                printf '%s' "$val" | tr -d '\r\n'
                return 0
            fi
        done
    done
    return 0
}

# ---------------------------------------------------------------------------
# normalise() — strip whitespace, lowercase
# ---------------------------------------------------------------------------
normalise() {
    printf '%s' "${1:-}" | tr -d '\r\n[:space:]'
}

# ---------------------------------------------------------------------------
# Collect identifiers
# ---------------------------------------------------------------------------
PLATFORM=$(read_prop "ro.board.platform" "ro.hardware" "ro.boot.hardware.platform")
HARDWARE=$(read_prop "ro.hardware" "ro.boot.hardware")
BRAND=$(read_prop \
    "ro.product.vendor.brand" \
    "ro.product.brand" \
    "ro.vendor.product.brand" \
    "ro.product.system.brand")
MANUFACTURER=$(read_prop \
    "ro.product.vendor.manufacturer" \
    "ro.product.manufacturer" \
    "ro.product.system.manufacturer")
MODEL=$(read_prop \
    "ro.product.vendor.model" \
    "ro.product.model" \
    "ro.product.system.model")
DEVICE=$(read_prop \
    "ro.product.vendor.device" \
    "ro.product.device" \
    "ro.boot.hardware")
FINGERPRINT=$(read_prop \
    "ro.vendor.build.fingerprint" \
    "ro.build.fingerprint" \
    "ro.bootimage.build.fingerprint")
VENDOR_API=$(read_prop "ro.vendor.api_level" "ro.vndk.version")
ANDROID_VERSION=$(read_prop "ro.build.version.release" "ro.system.build.version.release")
SOC_MODEL=$(read_prop "ro.soc.model" "ro.boot.product.hardware.sku")
SOC_MANUFACTURER=$(read_prop "ro.soc.manufacturer" "ro.boot.bootloader")
TREBLE_ENABLED=$(read_prop "ro.treble.enabled")

# ---------------------------------------------------------------------------
# Heuristic SoC vendor (independent of SoC manufacturer prop)
# ---------------------------------------------------------------------------
SOC_VENDOR="unknown"
__pl=$(printf '%s' "$PLATFORM" | tr '[:upper:]' '[:lower:]')
case "$__pl" in
    msm*|kona*|lahaina*|taro*|sm[0-9]*|sdm*|qcom*|holi*|bengal*|trinket*|atoll*) SOC_VENDOR="qcom" ;;
    mt6*|mt8*|mt[68]*) SOC_VENDOR="mtk" ;;
    exynos*|universal*|s5e*) SOC_VENDOR="exynos" ;;
    kirin*|hi3*) SOC_VENDOR="hisilicon" ;;
    ums*|sp9*|sc9*|t6*) SOC_VENDOR="unisoc" ;;
    gs[0-9]*|zuma*|whitechapel*) SOC_VENDOR="google" ;;
    rk*|rockchip*) SOC_VENDOR="rockchip" ;;
    *) SOC_VENDOR="unknown" ;;
esac

# ---------------------------------------------------------------------------
# Vendor partition fingerprint (for cache invalidation)
# ---------------------------------------------------------------------------
if [ -r /vendor/build.prop ]; then
    VENDOR_FP=$(sha256sum /vendor/build.prop 2>/dev/null | awk '{print $1}')
else
    VENDOR_FP="unknown"
fi

# ---------------------------------------------------------------------------
# Emit env file (sourced by compat-engine.sh)
# ---------------------------------------------------------------------------
{
    echo "# Auto-generated by compat/lib/detect-platform.sh"
    echo "COMPAT_PLATFORM=\"${PLATFORM}\""
    echo "COMPAT_HARDWARE=\"${HARDWARE}\""
    echo "COMPAT_BRAND=\"${BRAND}\""
    echo "COMPAT_MANUFACTURER=\"${MANUFACTURER}\""
    echo "COMPAT_MODEL=\"${MODEL}\""
    echo "COMPAT_DEVICE=\"${DEVICE}\""
    echo "COMPAT_FINGERPRINT=\"${FINGERPRINT}\""
    echo "COMPAT_VENDOR_API=\"${VENDOR_API}\""
    echo "COMPAT_ANDROID_VERSION=\"${ANDROID_VERSION}\""
    echo "COMPAT_SOC_MODEL=\"${SOC_MODEL}\""
    echo "COMPAT_SOC_MANUFACTURER=\"${SOC_MANUFACTURER}\""
    echo "COMPAT_SOC_VENDOR=\"${SOC_VENDOR}\""
    echo "COMPAT_TREBLE_ENABLED=\"${TREBLE_ENABLED}\""
    echo "COMPAT_VENDOR_FP=\"${VENDOR_FP}\""
} > "$COMPAT_PROP_ENV"

# ---------------------------------------------------------------------------
# Emit JSON snapshot (consumed by /run/ubuntu-gsi/compat-status.json)
# ---------------------------------------------------------------------------
json_escape() {
    printf '%s' "${1:-}" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/\t/\\t/g' \
                                -e 's/\r//g' -e ':a;N;$!ba;s/\n/\\n/g'
}

{
    echo '{'
    echo "  \"platform\":         \"$(json_escape "$PLATFORM")\","
    echo "  \"hardware\":         \"$(json_escape "$HARDWARE")\","
    echo "  \"brand\":            \"$(json_escape "$BRAND")\","
    echo "  \"manufacturer\":     \"$(json_escape "$MANUFACTURER")\","
    echo "  \"model\":            \"$(json_escape "$MODEL")\","
    echo "  \"device\":           \"$(json_escape "$DEVICE")\","
    echo "  \"fingerprint\":      \"$(json_escape "$FINGERPRINT")\","
    echo "  \"vendor_api\":       \"$(json_escape "$VENDOR_API")\","
    echo "  \"android_version\":  \"$(json_escape "$ANDROID_VERSION")\","
    echo "  \"soc_model\":        \"$(json_escape "$SOC_MODEL")\","
    echo "  \"soc_manufacturer\": \"$(json_escape "$SOC_MANUFACTURER")\","
    echo "  \"soc_vendor\":       \"$(json_escape "$SOC_VENDOR")\","
    echo "  \"treble_enabled\":   \"$(json_escape "$TREBLE_ENABLED")\","
    echo "  \"vendor_fp\":        \"$(json_escape "$VENDOR_FP")\""
    echo '}'
} > "$COMPAT_PROP_SNAPSHOT"

# ---------------------------------------------------------------------------
# When sourced via `source detect-platform.sh`, expose the variables in the
# caller's shell. When invoked directly, just print the env file path.
# ---------------------------------------------------------------------------
if (return 0 2>/dev/null); then
    # shellcheck source=/dev/null
    . "$COMPAT_PROP_ENV"
else
    echo "$COMPAT_PROP_ENV"
fi
