# /waydroid/lxc-seccomp.conf
# =============================================================================
# Baseline Seccomp V2 Sandbox for Universal Waydroid Multi-Container
# =============================================================================
2
blacklist
reject_force_umount  # Protect Host Overlays
[all]
# Drop capabilities risking Ubuntu rootfs integrity mapping
kexec_load errno 1
open_by_handle_at errno 1
init_module errno 1
finit_module errno 1
delete_module errno 1
